GET http://localhost:3001/api/comments

###
GET http://localhost:3001/api/comments/abc
###
GET http://localhost:3001/api/comments/issue/1

###
POST http://localhost:3001/api/comments/
Content-Type: application/json

{
  "issue_id":"1",
  "user_id":"5",
  "description":"New issue"
}

###
PATCH http://localhost:3001/api/comments/27
Content-Type: application/json

{
  "description":"THISISPATCHEDAGAIN"
}

###
DELETE http://localhost:3001/api/comments/26
