GET http://localhost:3000/api/issues

###
GET http://localhost:3000/api/issues/2

###
GET http://localhost:3000/api/issues/projects/5

###
POST http://localhost:3000/api/issues/
Content-Type: application/json

{
  "project_id":"6",
  "priority_id":"00",
  "user_id":"12",
  "status_id":"1",
  "title":"dligfdhkdfgfhkdf",
  "description":"data security breach",
  "report_date":"2004-10-19T08:23:54.000Z"
}

###
PATCH http://localhost:3000/api/issues/2
Content-Type: application/json

{
  "priority_id":"11",
  "status_id":"1",
  "title":"security breach",
  "description":"data security "
}

###
DELETE http://localhost:3000/api/issues/20