GET http://localhost:3000/api/projects

###
GET http://localhost:3000/api/projects/70

###
POST http://localhost:3000/api/projects/
Content-Type: application/json

{
  "project_name":"hello",
  "description":"hello world"
}

###
PATCH http://localhost:3000/api/projects/5
Content-Type: application/json

{
  "project_name":"hello3",
  "description":"hello world3"
}

###
DELETE http://localhost:3000/api/projects/4