GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/12


###
POST http://localhost:3000/api/users/
Content-Type: application/json

{
  "role_id":"1",
  "user_fName":"dfgfd",
  "user_lName": "fdgf",
  "email":"junyang@dfgd.com",
  "password":"dsfsd"
}

###
PATCH http://localhost:3000/api/users/5
Content-Type: application/json

{
  "role_id":"1",
  "user_fName":"Webber",
  "user_lName":"Jiang",
  "email":"dsgfd",
  "password":"12345"
}

###
DELETE  http://localhost:3000/api/users/3