GET http://localhost:3000/api/roles

###
GET http://localhost:3000/api/roles/3

###
POST http://localhost:3000/api/roles/
Content-Type: application/json

{
  "role_id":"10",
  "role_title":"hdsds"
}

###
PATCH http://localhost:3000/api/roles/2
Content-Type: application/json

{
  "role_title":"backend dev"
}

###
DELETE http://localhost:3000/api/roles/8